### PR TITLE
Adds support for Danish language

### PR DESCRIPTION
**Pull request by PJ789**
KeyboardLayout_da_DK.cpp is ordinary Danish keyboard layout
Keyboard.h references da_DK.cpp
Keyboard_da_DK.h defines scan codes for special Danish characters such as ÆØ.

### CODE REVIEW

**Comment by PJ789** [comment]
Hi @edgar-bonet ... please could I ask you to review & approve my changes again? Hopefully should be quicker/easier this time; the Swedish layout is almost identical. Main differences are the | character placement, and the Æ & Ø characters versus Ä & Ö.

**Comment by edgar-bonet** [comment]
I looked up three sources: [Wikipedia][], an [interactive layout comparator][cmp], and the layouts provided by my OS. They all agree that, within the ASCII repertoire, there are two differences between the Swedish and the Danish layouts:

| character | Swedish                | Danish                 |
|-----------|------------------------|------------------------|
| `\|`       | AltGr–<, `0x32\|ALT_GR` | AltGr–′, `0x2e\|ALT_GR` |
| `\`       | AltGr–+, `0x2d\|ALT_GR` | AltGr–<, `0x32\|ALT_GR` |

This pull request addresses `|` but leaves `\` in its Swedish position (AltGr–+ = `0x2d|ALT_GR`). It seems to me this is missing:

```diff
--- a/src/KeyboardLayout_da_DK.cpp
+++ b/src/KeyboardLayout_da_DK.cpp
@@ -99,7 +99,7 @@ extern const uint8_t KeyboardLayout_da_DK[128] PROGMEM =
        0x1c|SHIFT,    // Y
        0x1d|SHIFT,    // Z
        0x25|ALT_GR,   // [
-       0x2d|ALT_GR,   // bslash
+       0x32|ALT_GR,   // bslash
        0x26|ALT_GR,   // ]
        0x00,          // ^  not supported (requires dead key + space)
        0x38|SHIFT,    // _
```

You may want to check that `Keyboard.write('\\');` does type a backslash.

[Wikipedia]: https://en.wikipedia.org/wiki/QWERTY#Danish
[cmp]: http://www.farah.cl/Keyboardery/Interactive-Comparator-of-Different-National-Layouts/?left=sv&right=da

**Comment by PJ789** [comment]
Agreed.

**Comment by PJ789** [comment]
Confirmed your suspicion... I'll make that change.. Thanks @edgar-bonet .

**Comment by PJ789** [comment]
@facchinm please could you add this pull request? @edgar-bonet has reviewed (and improved).

**Comment by PJ789** [comment]
Recreating this pull request... because can't revert an accidental commit :( due to limitations of github.com

**Pull request closed without merging**
