### PR TITLE
Make public the `sendReport´function.

### PR DESCRIPTION
**Pull request by crushedice2000**
I think that `sendReport` is very useful and should be public. It could be kept undocumented, but at least to be available for some custom functions.

### CODE REVIEW

**Comment by facchinm** [comment]
Hi @crushedice2000 ,
now that the entire USB subsystem is modular we decided to keep the base Keyboard and Mouse libraries as simple as possible, leaving advanced/non-obvious features to external libraries (like @NicoHood 's HID https://github.com/NicoHood/HID ).
`sendReport` has never been public because its usage is non obvious, thus I wouldn't add it to public APIs

**Comment by crushedice2000** [comment]
@facchinm: I consider it obvious, however, is the only workaround to type special characters on non-US layouts. Could we work in creating a simple way to add keyboard layouts to the keyboard library?

Example of usage after implementation:

    Keyboard.begin() // For US layout
    Keyboard.begin(LAYOUT_SPANISH)
    Keyboard.begin(LAYOUT_GERMAN)
    Keyboard.begin(LAYOUT_ITALIAN)
    Keyboard.begin(LAYOUT_FRENCH)
    Keyboard.begin(LAYOUT_CUSTOM, layout_array)

**Comment by crushedice2000** [comment]
How can I remove my pull request?

**Comment by crushedice2000** [comment]
Also, why there are two ways to specify modifiers? (one way is to OR them in the report modifiers and the another way is to specify them as keys)?

**Comment by facchinm** [comment]
To add a modifier key you only need something like
```arduino
Keyboard.press(KEY_LEFT_ALT);
Keyboard.press('l');
Keyboard.releaseAll();
```
About supporting different layouts, it would be a nice addition but keeping this library lightweight is a must. I believe Nico's library already supports different keylayouts (and more advanced features).

**Comment by crushedice2000** [comment]
@facchinm, in the Nico library, it says that layouts aren't implemented yet. However I consider that layouts are a basic functionality. What about adding a folder with layouts and then use `#ifndefs` to build only the selected layout (at compile time)?

**Comment by facchinm** [comment]
Unfortunately we still cannot add `#defines` to a sketch and propagate them to libraries (there are a lot of proposals in this field but no decision has been taken yet).
So every addition to the library brings
- bigger footprint or
- forcing the user to activate/deactivate functionalities directly on the library headers :disappointed: 

Leaving these functionalities to external libraries keeps this one lightweight and easy to understand, suitable for users without specific needs. Nico's one is growing fast and I believe it will become feature-complete soon.

**Comment by crushedice2000** [comment]
Ok, so all Arduino users buy US keyboards? :stuck_out_tongue_closed_eyes: 

What about `Keyboard.begin()` to use US layout or `Keyboard.begin(keymap_array_imported_with_a_include)` for another layout? Is that factible?

I can't understand that simplicity aim :grinning: However, this seems good. The only thing I dislike is the lack of I2C support in LiquidCrystal and this lack of keyboard layouts. :laughing:

**Pull request closed without merging**
